# Generated by Django 3.2.16 on 2025-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20251025_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
